"""Every data file the book points at must actually exist.

Exercise sheets name specific images. A renamed or regenerated file that nobody
updated in the prose is invisible until a student hits it in the room, so it is
checked here instead.
"""

import re
from pathlib import Path

import pytest

REPO = Path(__file__).resolve().parents[2]
BOOK = REPO / "book"

DATA_REF = re.compile(r"`(data/[^`]+?\.(?:tif|tiff|png|gif|csv|model))`")
MACRO_REF = re.compile(r"`(macros/[^`]+?\.ijm)`")
LINK_REF = re.compile(r"\]\(([A-Za-z0-9_./-]+\.md)\)")

#: Everything the book references now exists.
KNOWN_MISSING: set[str] = set()

PAGES = sorted(BOOK.rglob("*.md"))


def _refs(pattern):
    out = []
    for page in PAGES:
        for match in pattern.findall(page.read_text(encoding="utf-8")):
            out.append((page, match))
    return out


@pytest.mark.parametrize(
    "page,ref",
    _refs(DATA_REF),
    ids=[f"{p.name}:{r}" for p, r in _refs(DATA_REF)],
)
def test_data_reference_exists(page, ref):
    if ref in KNOWN_MISSING:
        pytest.skip(f"{ref} is generated by hand in Fiji before the course")
    assert (REPO / ref).exists(), f"{page.name} references missing {ref}"


@pytest.mark.parametrize(
    "page,ref",
    _refs(MACRO_REF),
    ids=[f"{p.name}:{r}" for p, r in _refs(MACRO_REF)],
)
def test_macro_reference_exists(page, ref):
    assert (REPO / ref).exists(), f"{page.name} references missing {ref}"


@pytest.mark.parametrize(
    "page,ref",
    _refs(LINK_REF),
    ids=[f"{p.name}:{r}" for p, r in _refs(LINK_REF)],
)
def test_internal_link_resolves(page, ref):
    assert (page.parent / ref).resolve().exists(), f"{page.name} links to missing {ref}"
